# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('R', 'RED'), ('B', 'BLUE'), ('G', 'GREEN'), ('Y', 'YELLOW')], max_length=1), max_length=4, size=None)),
                ('ended', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('R', 'RED'), ('B', 'BLUE'), ('G', 'GREEN'), ('Y', 'YELLOW')], max_length=1), max_length=4, size=None)),
                ('black_pegs', models.IntegerField(null=True)),
                ('white_pegs', models.IntegerField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
    ]
