# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('R', 'RED'), ('B', 'BLUE'), ('G', 'GREEN'), ('Y', 'YELLOW')], max_length=1), size=4),
        ),
        migrations.AlterField(
            model_name='round',
            name='code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('R', 'RED'), ('B', 'BLUE'), ('G', 'GREEN'), ('Y', 'YELLOW')], max_length=1), size=4),
        ),
    ]
