# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170930_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='group',
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.Game', verbose_name='Game'),
            preserve_default=False,
        ),
    ]
