# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170930_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ended',
        ),
        migrations.AddField(
            model_name='game',
            name='n_rounds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='black_pegs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='white_pegs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
